### ISSUE TITLE
Request to help maintain module

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/masquerade#2]
Thanks for porting the module! @JugglingCoder I would like to help maintain this module to ensure it's ready for an official release.

I'm following the guidelines https://github.com/backdrop-ops/contrib to ensure first that as the maintainer you're okay with adding me to the README as a maintainer.

Thank you.

**Comment by JugglingCoder** [comment]
Sure herbdool, please do as you wish.  I'm one of those people who is doing a million things and although I love backdrop I just don't have time to address issues at this stage in time (I just port, create as I need them).  So, YES, I am ok with you doing whatever.  Not sure if I have to do anything? Add you somewhere? or just say "yes"?

**Comment by klonos** [comment]
@herbdool I'd take that as a "yes" 😄 Since you are already a contrib author, you have access to every contrib repo, so no need for anything special. Just add your name to the list of maintainers in the README and contrib away!!

**Comment by herbdool** [comment]
Thanks @JugglingCoder I've made a few small fixes and added my name.
